[project]
name = "discord"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "prompt-toolkit>=3.0.52",
    "rich>=14.2.0",
    "textual>=6.5.0",
    "typer>=0.20.0",
]
